### ISSUE TITLE
你好 请问一下貌似失效了

### ISSUE THREAD

**Issue by lone0x0** [damit5/xray_crack#1]
![截屏2022-05-23 13 28 54](https://user-images.githubusercontent.com/78702504/169749640-f8d6e65e-bdd8-48ad-8b8d-7cb2e1052160.png)

**Comment by damit5** [comment]
刚试了下没问题的哈，运行用 ./crack_mac.sh xray参数即可
<img width="1745" alt="图片" src="https://user-images.githubusercontent.com/32387710/169948126-a5606704-9486-436b-8fbc-44ffed9f5294.png">

**Comment by hailan09** [comment]
我这边为什么运行后是社区版的。。。
<img width="554" alt="image" src="https://user-images.githubusercontent.com/67746957/187343697-bb7fcb66-76b9-416d-ab74-e5d6baff08ca.png">

**Comment by hailan09** [comment]
我这边为什么启动后是社区版的。。。
![1661831000245](https://user-images.githubusercontent.com/67746957/187344490-ac23b562-ba9f-4a90-9990-d12bfe446716.jpg)
